version: '2.1'

services:
  react-cosmosdb:
    image: react-cosmosdb
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3001
      - 9229:9229
    ## set your startup file here
    command: node --inspect app.js